package by.htp.controller.command;

public enum CommandName {
	REGISTRATION, 
	LOGINATION, 
	SAVENEWUSER, 
	GOTOINDEXPAGE,
	GOTOSIGNINPAGE,
	GOTOMAINPAGE,
	GOTOABOUTPAGE,
	LOGOUT,
	SHOWNEWS,
	GOTOEDITNEWSPAGE,
	SAVEEDITEDNEWS,
	DELETENEWS,
	GOTOADDNEWSPAGE,
	INSERTNEWNEWS,
}
